# accounts/urls.py

from django.urls import path, include
from .views import RegisterView, LoginView, ProfileView
from rest_framework.routers import DefaultRouter
from .views import RegisterView, LoginView, ProfileView, FollowViewSet

# New Router for FollowViewSet
router = DefaultRouter()

router.register(r'users', FollowViewSet)
urlpatterns = [
    # Authentication endpoints
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    
    # Profile endpoint
    path('profile/', ProfileView.as_view(), name='profile'),
    
    # Follow/Unfollow Endpoints (Generated by router)
    path('', include(router.urls)),
]