# posts/urls.py

from rest_framework.routers import DefaultRouter
from django.urls import path, include
# FollowViewSet should NOT be here.
from .views import PostViewSet, CommentViewSet, FeedView 

# Create a router instance
router = DefaultRouter()

# Register ViewSets with the router
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    # Feed Endpoint
    path('feed/', FeedView.as_view(), name='feed'),
    
    # Include all paths generated by the router
    path('', include(router.urls)),
]