
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import PostViewSet, CommentViewSet

# Create a router instance
router = DefaultRouter()

# Register ViewSets with the router
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    # Include all paths generated by the router
    path('', include(router.urls)),
]