# posts/urls.py

from rest_framework.routers import DefaultRouter
from django.urls import path, include

# FollowViewSet should NOT be here.
from .views import PostViewSet, CommentViewSet, FeedView

# Create a router instance
router = DefaultRouter()

# Register ViewSets with the router
router.register(r"posts", PostViewSet)
router.register(r"comments", CommentViewSet)

urlpatterns = [
    
    path("feed/", FeedView.as_view(), name="feed"),
   
    path(
        "posts/<int:pk>/like/", PostViewSet.as_view({"post": "like"}), name="post_like"
    ),
    # unlike path
    path(
        "posts/<int:pk>/unlike/",
        PostViewSet.as_view(
            {"post": "like"}
        ),  
        name="post_unlike",  
    ),
    # Include all paths generated by the router
    path("", include(router.urls)),
]
